### ISSUE TITLE
Anomaly detection - AUC for quantized model with INT8 input/output

### ISSUE THREAD

**Issue by MiguelCosta94** [mlcommons/tiny#110]
Hi,

Regarding the anomaly detection, what is the expected AUC for the quantized model with INT8 input/output (ad01_int8.tflite or model_ToyCar_quant_fullint_micro_intio.tflite)? I am getting an AUC of 0.354 for the machine ID 0, which is very low when compared to the AUC for the quantized model, but with float input/output (model_ToyCar_quant_fullint_micro.tflite).

**Comment by cskiraly** [comment]
Hi @MiguelCosta94 
It is around 0.85 as documented in https://github.com/mlcommons/tiny/tree/master/v0.5
The difference to float is actually little, so there should be something other problem in your setup.

**Comment by MiguelCosta94** [comment]
Hi @cskiraly 
It was a problem in my setup. Thanks for the reply.
