### ISSUE TITLE
fatal error: 'model.h' file not found

### ISSUE THREAD

**Issue by ThomasGmeinder** [mlcommons/tiny#22]
Hi 
I'm trying to build tiny/v0.1 and "make" causes an error:
example_submission/model.cc:15:10: fatal error: 'model.h' file not found

Please find a more detailes below.
Is this error expected or caused by a user error?
Thanks, Thomas

Host info:
Mac OS 10.15.7
g++ --version
Configured with: --prefix=/Applications/Xcode.app/Contents/Developer/usr --with-gxx-include-dir=/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include/c++/4.2.1
Apple clang version 12.0.0 (clang-1200.0.32.29)
Target: x86_64-apple-darwin19.6.0
Thread model: posix
InstalledDir: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin

Detailed trace:
  inflating: tensorflow-master/third_party/vulkan_headers/workspace.bzl  
  inflating: tensorflow-master/third_party/wrapt.BUILD  
  inflating: tensorflow-master/third_party/zlib.BUILD  
   creating: tensorflow-master/tools/
  inflating: tensorflow-master/tools/tf_env_collect.sh  
finishing deferred symbolic links:
  tensorflow-master/.pylintrc -> tensorflow/tools/ci_build/pylintrc
mv: rename tensorflow-master/tensorflow to ./tensorflow: Directory not empty
tensorflow/lite/micro/tools/make/Makefile:17: *** "Requires make version 3.82 or later (current is 3.81)".  Stop.
tensorflow/lite/micro/tools/make/Makefile:17: *** "Requires make version 3.82 or later (current is 3.81)".  Stop.
mv: rename tensorflow/lite/micro/tools/make/gen/*/lib/libtensorflow-microlite.a to ./libtensorflow-microlite.a: No such file or directory
'g++' -DTF_LITE_STATIC_MEMORY -DNDEBUG -O3 -DTF_LITE_DISABLE_X86_NEON -Iexample_submission -Iexample_submission/third_party/gemmlowp -Iexample_submission/tensorflow/lite/micro/tools/make/downloads/flatbuffers/include -Iexample_submission/third_party/ruy -std=c++11 -I.  -c example_submission/model.cc -o example_submission/model.o
example_submission/model.cc:15:10: fatal error: 'model.h' file not found
#include "model.h"
         ^~~~~~~~~
1 error generated.
make: *** [example_submission/model.o] Error 1

**Comment by colbybanbury** [comment]
Hi Thomas,

The benchmark is still under construction and specifically the reference submissions are still being worked on.

I just merged a PR that made a fair number of changes to the visual wake words example so that may have resolved the issue. If you belong to an organization that would like to submit to TinyMLPerf please see the call for [submission for more information](https://docs.google.com/document/d/1eGox5GYXc9BUtl9764D8USsKQsSeKYdmJKxCdL8zMWs/edit?usp=sharing)

**Comment by ThomasGmeinder** [comment]
Hi Colby
I work for XMOS and we have registered to submit to TinyMLPerf. We are planning to measure the performance that can be achieved on our xCORE.ai processor. 

I'm trying to build the main.cpp as a baseline and then optimise the tflite model for our architecture (we developed a tool for this). Is that the way to do it?

I did a git pull to get the latest but when I execute "make" I get a new error:
Makefile:19: example_submission/Makefile.inc: No such file or directory

Kind regards, Thomas

**Comment by colbybanbury** [comment]
Hi Thomas,

That sounds like the right way to do it. We are still in the process of polishing up our reference submissions (sorry for the delay) but they should be up very soon with instructions on how to use them. 

The reference submissions are built using TFLite for Microcontrollers and Mbed. Does that work for your platform?
