### ISSUE TITLE
'image_classification' returned "Too few timestamps found for performance check" by EEMBC Benchmark Runner

### ISSUE THREAD

**Issue by AnXelion** [mlcommons/tiny#65]
Hi, 

I compiled **[image_classification](https://github.com/mlcommons/tiny/tree/master/v0.1/reference_submissions/image_classification)** in [reference_submission](https://github.com/mlcommons/tiny/tree/master/v0.1/reference_submissions) and copied the bin file to [NUMAKER_IOT_M487](https://os.mbed.com/platforms/NUMAKER-IOT-M487/).

Then, I tried to run [EEMBC Benchmark Runner](https://github.com/eembc/benchmark-runner-ml) with script **ML Performance 1.0.0**. 

I got message 
```
ulp-mlperf: Too few timestamps found for performance check.
ulp-mlperf: Cannot compute accuracy metrics in single-run mode.
```
  
Is there anything that I missed to set in order to run the test correctly on an Mbed supported board? Thanks!

**Comment by colbybanbury** [comment]
Those sound like the right steps. Not sure what causes that error. Let me loop in the experts on the runner and IC benchmark.

@PieMonty and @petertorelli have either of you encountered this error? Any advice

**Comment by PieMonty** [comment]
Hi AnXelion,

are you working on Windows, Mac or Linux?
Try increasing the **Inference Iterations** when using the single run mode.
Also, you should run in **Multiple** mode for performance evaluation.

**Comment by AnXelion** [comment]
Hi @PieMonty,

I'm working on Mac with macOS Mojave 10.14.6 (18G8022).

I have changed to the setting as the following pic, but still get the same message in both the **single mode** and the **benchmark mode**.
![](https://i.imgur.com/PrBqI7u.jpeg)
![](https://imgur.com/7K3lN2y.jpeg)

However, if I run the same setting in the multiple mode, I got the following message which said 
```
ulp-mlperf: Not all of the inputs had an output result
```
![](https://imgur.com/DQz9yuI.jpeg)


Thanks for all the replies. Really appreciate it.

**Comment by petertorelli** [comment]
Something is wrong with your implementation: it is initializing when you call infer. Initialization should be done as soon as it powers up, not when you call infer.

**Comment by petertorelli** [comment]
My guess is that you have a bug in inference that is causing the device to reboot.

**Comment by AnXelion** [comment]
Hi @petertorelli, 

Thanks for the quick reply. 

I didn't do any change to the source code in image_collection. All I changed was setting MBed's baud rate to 115200 in mbed_app.json. Then I just compiled the code into numaker-iot-m487's bin file and flash it to the board.

Maybe I should do some changes to the source code in image_classification in reference_submissions?

**Comment by petertorelli** [comment]
Can't really tell where the problem is. Try mounting the DUT directly and sending it commands. E.g, from the User Console: `mountc dut dut` and then `dut name`. If it prints "m-name-dut..." and then "m-ready" then the problem is with the infer code. If you can't talk to it at all, the problem is with your init code. Since the timestamp is "zero" I suspect nothing is ported correctly because it is highly unlikely zero microseconds elapsed from the time the device booted to the time `th_timestamp` is invoked. I recommend familiarizing yourself with the code and the documentation first, to get a sense of what is actually expected.

**Comment by PieMonty** [comment]
Thank you @petertorelli for additional info.
Thank you @AnXelion for trying the code out.
We found a potential issue that could lead to what you were seeing and we changed the code accordingly.
I encourage you to clone the repository again, make sure the build process is completed without errors and try to use the EEMBC Benchmark Runner for performance evaluation again.
We look forward to hearing from you.

**Comment by AnXelion** [comment]
Hi @petertorelli and @PieMonty ,

I tried the suggestions @petertorelli mentioned  
>  Try mounting the DUT directly and sending it commands. E.g, from the User Console: mountc dut dut and then dut name.

EEMBC Benchmark Runner could mount the device and dut could respond the name of the device.

I also tried to call `th_timestamp_initialize` and `th_timestamp` directly in main.cpp:
```
int main() {
  th_timestamp_initialize();
  th_timestamp();
  th_timestamp();
  th_timestamp();
   
  // comment out the original code
  /*
   ee_benchmark_initialize();
  while (1) {
    int c;
    c = th_getchar();
    ee_serial_callback(c);
  }
  /*
  return 0;
}
```
`th_timestamp` did respond **non zero value**.



I have also tried the suggestion @PieMonty kindly mentioned:
> I encourage you to clone the repository again, make sure the build process is completed without errors and try to use the EEMBC Benchmark Runner for performance evaluation again.

Unfortunately, the same problem still happens, which just like @petertorelli mentioned, the board do initialization every time I call infer.


Thanks for all the responses!

**Comment by PieMonty** [comment]
Hi @AnXelion ,

could you please share the mbed-os version you are using?
You should find it in tiny/v0.1/reference_submissions/image_classification/mbed-os/platform/include/platform/mbed_version.h

You should have this:
<pre>
#define MBED_MAJOR_VERSION 6

/** MBED_MINOR_VERSION
  * Mbed OS minor version
  *
  * @note 99 is default value for development version (master branch)
  */
#define MBED_MINOR_VERSION 3

/** MBED_PATCH_VERSION
  * Mbed OS patch version
  *
  * @note 99 is default value for development version (master branch)
  */
#define MBED_PATCH_VERSION 0
</pre>

**Comment by AnXelion** [comment]
Hi @PieMonty , 

It's like the following:
```
/** MBED_MAJOR_VERSION
  * Mbed OS major version
  *
  * @note 99 is default value for development version (master branch)
  */
#define MBED_MAJOR_VERSION 6

/** MBED_MINOR_VERSION
  * Mbed OS minor version
  *
  * @note 99 is default value for development version (master branch)
  */
#define MBED_MINOR_VERSION 3

/** MBED_PATCH_VERSION
  * Mbed OS patch version
  *
  * @note 99 is default value for development version (master branch)
  */
#define MBED_PATCH_VERSION 0

#define MBED_ENCODE_VERSION(major, minor, patch) ((major)*10000 + (minor)*100 + (patch))
```

**Comment by PieMonty** [comment]
Hi @AnXelion 
i see from the screenshot above you get this printed:
<pre>
m-timestamp-mode-energy
</pre>

I am using ubuntu 20 and this is what i see when i run the ML Performance 1.0.0 test in single run mode:
![image](https://user-images.githubusercontent.com/70531728/114987150-1e43af00-9e95-11eb-8650-bea710c343f5.png)

Can you make sure you are choosing ML Performance 1.0.0 and not ML Energy 1.0.0 as the benchmark test you want to run?

Let me know if this solves the problem
Thank you for your effort

**Comment by AnXelion** [comment]
Hi @PieMonty ,

I'm sure that I chose ML Performance 1.0.0 not  ML Energy 1.0.0 as the benchmark test. The following pics are screenshots I ran the test in single mode.

https://imgur.com/a/glFasDU


If I'm not wrong, it seems like `m-timestamp-mode-energy` might always be printed since it is defined in [submitter_implemented.h](https://github.com/mlcommons/tiny/blob/315be0a38973f2201a880c2576bb0b6522d60af8/v0.1/reference_submissions/image_classification/api/submitter_implemented.h#L40) 

```c++
#ifndef MLPERF_TINY_V0_1_API_SUBMITTER_IMPLEMENTED_H_
#define MLPERF_TINY_V0_1_API_SUBMITTER_IMPLEMENTED_H_

/// \brief These defines set logging prefixes for test harness integration.
/// \detail This API is designed for performance evaluation only. In order to
/// gather energy measurments we recommend using the EEMBC test suite.
#define EE_MSG_TIMESTAMP_MODE "m-timestamp-mode-energy\r\n"
```

and it will always be used in th_printf() in th_timestamp_initialize() in [submitter_implemented.cpp](https://github.com/mlcommons/tiny/blob/315be0a38973f2201a880c2576bb0b6522d60af8/v0.1/reference_submissions/image_classification/submitter_implemented.cpp#L196)

```C++
void th_timestamp_initialize(void) {
  /* USER CODE 1 BEGIN */
  // Setting up BOTH perf and energy here
  /* USER CODE 1 END */
  /* This message must NOT be changed. */
  th_printf(EE_MSG_TIMESTAMP_MODE);
  /* Always call the timestamp on initialize so that the open-drain output
     is set to "1" (so that we catch a falling edge) */
  th_timestamp();
}
```

By the way, the only change I made to the code in `mbed_app.json` is adding `"platform.stdio-baud-rate": 115200`, and `"platform.default-serial-baud-rate": 115200`

```
"target_overrides": {
        "*": {
            ...
            "platform.stdio-baud-rate": 115200,
            "platform.default-serial-baud-rate": 115200
        }
    }
```

Thank you again!

**Comment by petertorelli** [comment]
It appears a few lines of code were lost during the EEMBC to Google translation, [here is the original](https://github.com/eembc/testharness-ulpmark-ml/blob/60be856053a82a7a688d9fe790e83378e6468b21/monitor/th_api/th_lib.h#L29-L33), it should have been:

```
#if EE_CFG_ENERGY_MODE == 1
#define EE_MSG_TIMESTAMP_MODE "m-timestamp-mode-energy\r\n"
#else
#define EE_MSG_TIMESTAMP_MODE "m-timestamp-mode-performance\r\n"
#endif
```

However, that is just there as a reminder to the user when booting the device, and not used by the runner, so it shouldn't be a problem, but should be cleaned up.

**Comment by AnXelion** [comment]
Hi @PieMonty and @petertorelli,

Could you kindly provide which boards have successfully run the code in reference folder? I decide to buy a new board for testing my trained model with the benchmark.

Thanks!

**Comment by PieMonty** [comment]
Hi @AnXelion ,

this is the board we used for testing the reference benchmarks:
https://www.st.com/en/evaluation-tools/nucleo-l4r5zi.html

Let us know if you encounter any issue with that.
Many thanks for your patience

**Comment by petertorelli** [comment]
Can we close this issue now?

**Comment by AnXelion** [comment]
Hi,

After I switched to another board, everything worked fine. I believe it's  NUMAKER_IOT_M487's problem. 

Again, thank you all for all your support.
