### ISSUE TITLE
anomaly in get_dataset.sh for anomaly_detection?

### ISSUE THREAD

**Issue by scrouzet** [mlcommons/tiny#78]
The sh file `tiny/v0.1/training/anomaly_detection/get_dataset.sh` seems to write data files supposed to be used for eval in the training data directory.

```bash
#!/bin/sh

URL1="https://zenodo.org/record/3678171/files/dev_data_ToyCar.zip?download=1"
ZIPFILE="dev_data_ToyCar.zip"

URL2="https://zenodo.org/record/3727685/files/eval_data_train_ToyCar.zip?download=1"

mkdir -p dev_data

curl $URL1 -o $ZIPFILE || wget $URL1 -O $ZIPFILE
unzip $ZIPFILE -d dev_data
rm $ZIPFILE

curl $URL2 -o $ZIPFILE || wget $URL2 -O $ZIPFILE
unzip $ZIPFILE -d dev_data
rm $ZIPFILE
```

Should be:

```bash
#!/bin/sh

URL1="https://zenodo.org/record/3678171/files/dev_data_ToyCar.zip?download=1"
ZIPFILE="dev_data_ToyCar.zip"

URL2="https://zenodo.org/record/3727685/files/eval_data_train_ToyCar.zip?download=1"

mkdir -p dev_data

curl $URL1 -o $ZIPFILE || wget $URL1 -O $ZIPFILE
unzip $ZIPFILE -d dev_data
rm $ZIPFILE

curl $URL2 -o $ZIPFILE || wget $URL2 -O $ZIPFILE
unzip $ZIPFILE -d eval_data
rm $ZIPFILE
```

Or is it wanted? You don't mind about evaluation here so you take advantage of all the data for training?

**Comment by cskiraly** [comment]
Hi @scrouzet 

That indeed could be a problem, thanks for pointing out!

However, if you look at the description on Zenodo, the file itself contains "additional training dataset", and this is not what we use for the evaluation. The naming is coming from the way the DCASE competition was set up, where this was the first training dataset released for the machine IDs that were later used for their evaluation.

We trained the reference model on normal samples from machine IDs 1-4 (first zip file) and machine IDs 5-7 (the second zip file). We evaluate performance on a mix of normal and anomaly samples (a different set), from IDs 1-4 only. Training on 1-7 gave slightly better results than training on 1-4 only. 

I hope that answers your question. Let me know if you still see some problems.

**Comment by scrouzet** [comment]
Thanks for your detailed answer (and the work on this repo).
