### ISSUE TITLE
Facing "e-[Insufficient number of hex digits]" issue in accuracy mode

### ISSUE THREAD

**Issue by malreddy-commits-pixel** [mlcommons/tiny#79]
Facing below issue in "Multiple run mode(accuracy mode)" for anomaly detection. Below attached the screen shot which shows the error message.
  
![image](https://user-images.githubusercontent.com/83743545/117239318-2f585e00-ae4c-11eb-99d2-a41477ccee04.png)

Could you please take a look ?

**Comment by petertorelli** [comment]
Data was dropped in the UART path. If you look at the code [here](https://github.com/mlcommons/tiny/blob/a0778c8c56bb92652012db5b28818dd5d384a08d/v0.1/api/internally_implemented.cpp#L252-L264) you can see that a byte was dropped. 

```
  } else {
    size_t numbytes;
    char test[3];
    long res;


    /* Two hexdigits per byte */
    numbytes = th_strnlen(p_next, EE_CMD_SIZE);


    if ((numbytes & 1) != 0) {
      th_printf("e-[Insufficent number of hex digits]\r\n");
      return EE_ARG_CLAIMED;
    }
    test[2] = 0;
```

This can be cause by too high a baud rate, or an error in the Rx code, or an issue with the Host<>UART hardware driver (e.g., the Prolific USB<>TTL, SiLabs USB<>TTL, and STM VCP driver could be the issue).

Peter

**Comment by petertorelli** [comment]
Also, the latest 3.0.6 version has a setting in the ini file called `disable-mute`. Set that to true to disable muting the bload messages. This can help you identify when/where it is failing.

**Comment by shijay01** [comment]
Using baudrate of 115200 during compilation of the bin and for the runs solved the issue , though it is recommended in the reference submission's Readme that 921600 is the desirable baudrate.

**Comment by cskiraly** [comment]
Thanks @shijay01 . 921600 is recommended to speed up the accuracy test that downloads lots of data over serial. However, it seems the higher baud rate is not working on all systems. I'm glad 115200 solved it for you. I'm adding a note on this in the README https://github.com/mlcommons/tiny/pull/82

**Comment by petertorelli** [comment]
@shijay01 That is good news. Please close the issue if resolved. Cheers, Peter

**Comment by shijay01** [comment]
Thankyou @cskiraly and @petertorelli . Closing the issue.
