### ISSUE TITLE
Sample models

### ISSUE THREAD

**Issue by UpasanaSridhar** [mlcommons/tiny#8]
Hi I was wondering if you could tell me some of the model architectures you are considering for the benchmark.
If not, could you give me an ETA for when the benchmark will be released?

**Comment by colbybanbury** [comment]
Hi,

We are using the following models for our benchmarks:
Mobilenet for VWW
DS-CNN for AWW
FC autoencoder for AD
ResNet for image classification

Please join the google group for more information and to participate: https://groups.google.com/g/mlperf-tiny

We are currently in the process of uploading the models and refactoring the repo structure so stay tuned!
