### ISSUE TITLE
Inclusion of a LICENSE file.

### ISSUE THREAD

**Issue by JosephBushagour** [mlcommons/tiny#86]
Currently this repository doesn't have a top-level `LICENSE` or `LICENSE.md` file. Some source code files contain reference to the Apache License Version 2.0, but not all source code files include this and notably there is an [MIT license in the pre-trained anomaly detection model](https://github.com/mlcommons/tiny/blob/8fa7170e4f95ae369cfaaf695a14545848972267/v0.1/training/anomaly_detection/LICENSE). The [inclusion of a top-level `LICENSE` file](https://docs.github.com/en/communities/setting-up-your-project-for-healthy-contributions/adding-a-license-to-a-repository) would allow open source projects to utilize the `api`, `reference_submissions`, etc. without worrying about licensing issues.

**Comment by colbybanbury** [comment]
Great point!

@TheKanter What is the normal MLCommons policy around GitHub licenses?

**Comment by TheKanter** [comment]
We should have them. I'd look at training and inference as examples.
